name: Cypress Test and Deploy Custom Report to Vercel

on:
  schedule:
    - cron: '0 7 * * *' # Chạy lúc 7:00 AM UTC mỗi ngày
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate custom report
        run: |
          npx cypress run --headless # Chạy headless để tạo báo cáo ban đầu
          npm run generate-custom-report # Tạo file HTML tùy chỉnh

      - name: Commit and push custom report
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add cypress/reports/custom-report.html # Thay bằng đường dẫn file HTML tùy chỉnh của bạn
          git commit -m "Update custom Cypress test report" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Vercel URL
        run: |
          echo "VERCEL_URL=https://[your-vercel-project-name].vercel.app/custom-report.html" >> $GITHUB_ENV
        # Thay [your-vercel-project-name] bằng tên dự án Vercel của bạn