name: Cypress Test and Deploy Custom Report to Vercel

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử commit

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Debug changed files
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Files changed:"
          git diff --name-only HEAD^ HEAD || echo "No diff available"

      - name: Run Cypress conditionally
        continue-on-error: true
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "🕒 Cron job: chạy toàn bộ test"
            npm run test-and-report
          else
            echo "🚀 Push: kiểm tra file thay đổi"
            bash ./run-cypress-conditionally.sh
          fi

      - name: Commit and push custom report
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add cypress/custom-report/index.html
          git commit -m "Update custom Cypress test report" || echo "No changes to commit"
          git push || echo "Push failed or no changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Vercel URL
        run: echo "VERCEL_URL=https://hybrid-automation-framework.vercel.app" >> $GITHUB_ENV

      - name: Send email with report link
        uses: dawidd6/action-send-mail@v3
        with:
server_address: smtp.gmail.com
server_port: 465
username: ${{ secrets.EMAIL_USERNAME }}
password: ${{ secrets.EMAIL_PASSWORD }}
subject: "Daily Custom Cypress Test Report - ${{ github.run_id }}"
body: |
  Dear Sir/Madam,

  Please find below the customized Cypress test report with the following details:

  - Project name: {{ PROJECT_NAME }}
  - Environment: {{ ENVIRONMENT_NAME }}
  - Execution date: {{ RUN_DATE }}

  Report link: ${{ env.VERCEL_URL }}

  Sincerely,  
  Thu Tran
to: "duyvu2612003@gmail.com"
from: "Thu Tran <tranthuyminhthu0611@gmail.com>"
